# Generated by Django 5.2.13 on 2026-04-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_product_category'),
        ('shop', '0004_order'),
    ]

    operations = [
    ]
